### ISSUE TITLE
Thank you for the clover but i have an issue

### ISSUE THREAD

**Issue by ztuning** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Mojave-10.14.6-Hackintosh#2]
my notebook have same specs with yours, but im not able to deep sleep evertime i go deepsleep my notebook restart. what should i do ? and did you have an suggestion if i have to do manually patch my DSDT because so many guide outside there.
Best Regards

**Comment by whatnameisit** [comment]
Are you using the latest updated commits? If so, please use Hackintool to fix sleep by going to the Power tab and click the button on the bottom to see if the line highlighted in red changes to green. Or manually type in the 5 command lines found in this: https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/
Reboot, and see if that fixed the issue.

**Comment by ztuning** [comment]
well after following your idea now is not restart but shutdown 
here is my pmset -g log
![image](https://user-images.githubusercontent.com/47665987/71643309-9b700280-2cea-11ea-8a28-310832cdf317.png)

**Comment by whatnameisit** [comment]
Post your Clover folder with Clover extracted ACPI (F4 at

**Comment by ztuning** [comment]
here is the link, i upload it to gdrive
my clover and ACPI extract
[https://drive.google.com/file/d/1JFJNcBHeEO_GlFnf3Ll67-bnk-bH3jqG/view?usp=sharing](url)

**Comment by whatnameisit** [comment]
> well after following your idea now is not restart but shutdown
You didn't follow my idea. Download the latest git and update your EFI.

**Comment by ztuning** [comment]
Well i think ill close this issue because after i repatch again my original ACPI by myself the sleep working maybe there is different type of our motherboard.
Thank you mate

**Comment by whatnameisit** [comment]
It could be that you have a muxed GPU system like NVidia Optimus in which case you need to apply PTSWAK and DGPU patches found in tctien342's master branch.
Do you have such a system?
