### ISSUE TITLE
Problem to play Netflix (HEVC Problem)

### ISSUE THREAD

**Issue by Nevuly** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Mojave-10.14.6-Hackintosh#3]
안녕하세요, 오랜만에 이슈 트래픽을 남깁니다.
다름이 아니라 인텔 내장 그래픽에서 HEVC가 제대로 안잡히는것 같습니다.
Netflix에서 영화나 드라마를 시청하려면 HEVC가 지원을 해야하는데,
그게 제대로 지원이 되지 않는지 시청이 불가능한 상황이 발생하고 있습니다. (사파리와 3rd-party 앱 기준)
다행이 크롬에서는 시청이 그나마 가능하지만 720p이상은 시청이 불가능한 상황입니다.
혹시 인텔 프레임버퍼 패치할때 문제가 있었나 한번 확인 요청을 드리는 바입니다.
항상 작업 해 주시는 whatnameisit님께 감사드립니다.

추가 : whatevergreen의 이슈도 있다고 해서 devbulid를 올려서 videoproc으로 확인해 보면 HEVC는 잡히지만 넷플릭스는 구동이 되질 않습니다.

**Comment by whatnameisit** [comment]
WEG 1.4.6으로 VideoProc 테스트하면 Enabled로 나오지만 중간중간 로그에 invalid 등의 문구가 나오는데 HEVC가 제대로 안 되는 것 같네요. 10.15.2부터 AMD에서도 비슷한 문제가 있다고 한 것 같은데 시간이 되면 다른 OS에서도 테스트 해볼게요.

**Comment by whatnameisit** [comment]
10.14.6, WhateverGreen 1.3.5에서 오류 없이 HEVC Enabled로 표기됩니다.
그러나 여전히 사파리에서 Netflix가 안 되더군요.
WhateverGreen Shiki 매뉴얼에서는:
> Can I play HTML5 Netflix videos with Shiki?
> No, you cannot since Netflix limited their 1080p content for very few mac models even excluding most Mac Pros.
MBP15,2가 Netflix 지원되는 모델인지 확인해볼 필요가 있을까 생각이 듭니다.

**Comment by Nevuly** [comment]
MBP15,2 모델에서 지원하는것 같습니다. 아무래도 패치쪽에 문제인거 같긴한데......
일단 더 확인을 해봐야겠네요.

**Comment by Nevuly** [comment]
혹시 HDCP 부분 쪽 확인해보는건 어떨까요?
Netflix 스트리밍 오류 중에 HDCP와 HEVC 두개로 나뉘는것 같습니다.

**Comment by Nevuly** [comment]
참고로 https://help.netflix.com/ko/node/23742 해당 노드에서 나온 내용에 따르면 Mac은 2012년 이후 모델은 전부 지원이라고 나와있습니다.

**Comment by whatnameisit** [comment]
모하비에서 이것저것 해보고 있지만 잘 되지 않네요...
tctien342/hieplpvip의 그래픽 설정으로부터 제가 바꾼 것이라 하면 ACPI 그래픽 패치에서 IOReg 그래픽 패치로 바꾸고 HDMI output(con2) 가능하도록 설정하고 사용하지 않는 con1을 죽인 건데요. 기존 설정을 사용한다고 하더라도 별 차이는 없을 것 같습니다.
위에 언급했지만 VideoProc으로 테스트했을 때 10.15.2 HEVC 테스팅 로그가 invalid로 문제가 있는 것은 맞지만 10.14.x에서는 HEVC 로그가 정상적으로 보입니다.
사실 DRM이나 SilverLight이나 심지어 넷플릭스도 제가 전혀 안 쓰던 부분이라...어떤 식으로 연구해야되는지 감이 오지 않구요...차라리 다른 노트북 사용자중에 사파리로 넷플릭스 시청이 가능한지 물어보는게 더 빠를 것도 같습니다. 힘드네요 헿

**Comment by Nevuly** [comment]
음... 아이맥이나 AMD그래픽카드를 사용하는 해킨만 되는듯한 느낌입니다...ㅠㅠ..
여튼 확인해 주셔서 감사합니다 ㅠㅠ...
